# Generated by Django 5.0 on 2023-12-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=20)),
                ("code", models.TextField()),
                ("author", models.CharField(max_length=30)),
                ("pub_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=30)),
                ("pub_date", models.DateTimeField()),
                (
                    "code_sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checker.codesample",
                    ),
                ),
            ],
        ),
    ]
