# Generated by Django 5.0 on 2024-01-02 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("result_ai", models.CharField(max_length=200, null=True)),
                ("result_static", models.CharField(max_length=200, null=True)),
                ("author", models.CharField(max_length=30)),
                ("pub_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("abbr", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=30)),
                ("pub_date", models.DateTimeField()),
                (
                    "code_sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checker.codesample",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="codesample",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="checker.language",
            ),
        ),
    ]
